# AI4I 2020 PMD Ingest Pipeline
This notebook is desribed how ingest-AI4I-2020-PMD.py functions. It is used to pull the data provided (DOI 10.24432/C5HS5C) onto the local system through the use of UCI's mlrepo library, and provide simple verification of the data received

1. Imports and fetch

In [103]:
# imports
import pandas as pd                 # access to pandas feature set
import pyarrow as pa                # allows for saving to parquet (wasn't sure if we wanted to use that or regular csv)
import pyarrow.parquet as pq        # allows for accessing parquet files to check for consistency
from pathlib import Path            # cross-os compatability
from ucimlrepo import fetch_ucirepo # uc irvine library to fetch and format dataset

In [104]:
# establish save directories
RAW_DATA_DIR = Path("../data/raw")
RAW_DATA_DIR.mkdir(parents=True, exist_ok=True) # create folder if needed

PROC_DATA_DIR = Path("../data/processed")
PROC_DATA_DIR.mkdir(parents=True, exist_ok=True) # create folder if needed

fetch_ucirepo returns a dataset containing:

data: Contains dataset matrices as pandas dataframes
    ids: Dataframe of ID columns
    features: Dataframe of feature columns
    targets: Dataframe of target columns
    original: Dataframe consisting of all IDs, features, and targets
    headers: List of all variable names/headers
metadata: Contains metadata information about the dataset
    See Metadata section below for details
variables: Contains variable details presented in a tabular/dataframe format
    name: Variable name
    role: Whether the variable is an ID, feature, or target
    type: Data type e.g. categorical, integer, continuous
    demographic: Indicates whether the variable represents demographic data
    description: Short description of variable
    units: variable units for non-categorical data
    missing_values: Whether there are missing values in the variable's column
    
All of which is stored in a dotdict, requiring dot notation to access (i.e. dataset.data.features )

In [ ]:
# AI4I 2020 PMD dataset: 601
DATASET_ID = 601

# fetch dataset
ai4i_2020_pmd = fetch_ucirepo(id=DATASET_ID) 
  
# data (as pandas dataframes)
data = pd.DataFrame(ai4i_2020_pmd.data.original) 
  
# metadata 
print(ai4i_2020_pmd.metadata) 
  
# variable information 
print(ai4i_2020_pmd.variables)

{'uci_id': 601, 'name': 'AI4I 2020 Predictive Maintenance Dataset', 'repository_url': 'https://archive.ics.uci.edu/dataset/601/ai4i+2020+predictive+maintenance+dataset', 'data_url': 'https://archive.ics.uci.edu/static/public/601/data.csv', 'abstract': 'The AI4I 2020 Predictive Maintenance Dataset is a synthetic dataset that reflects real predictive maintenance data encountered in industry.', 'area': 'Computer Science', 'tasks': ['Classification', 'Regression', 'Causal-Discovery'], 'characteristics': ['Multivariate', 'Time-Series'], 'num_instances': 10000, 'num_features': 6, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['Machine failure', 'TWF', 'HDF', 'PWF', 'OSF', 'RNF'], 'index_col': ['UID', 'Product ID'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2020, 'last_updated': 'Wed Feb 14 2024', 'dataset_doi': '10.24432/C5HS5C', 'creators': [], 'intro_paper': {'ID': 386, 'type': 'NATIVE', 'title': 'Explainable Artificial Intelligence for Predictive Maintenance Applications', 'authors': 'S. Matzka', 'venue': 'International Conference on Artificial Intelligence for Industries', 'year': 2020, 'journal': None, 'DOI': '10.1109/AI4I49448.2020.00023', 'URL': 'https://www.semanticscholar.org/paper/b609c8e9ec6a2b8c642810953ef6dffe5766f7c1', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'Since real predictive maintenance datasets are generally difficult to obtain and in particular difficult to publish, we present and provide a synthetic dataset that reflects real predictive maintenance encountered in industry to the best of our knowledge.\r\n\r\n\r\n\r\n', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': "The dataset consists of 10 000 data points stored as rows with 14 features in columns\r\nUID: unique identifier ranging from 1 to 10000\r\nproduct ID: consisting of a letter L, M, or H for low (50% of all products), medium (30%) and high (20%) as product quality variants and a variant-specific serial number\r\nair temperature [K]: generated using a random walk process later normalized to a standard deviation of 2 K around 300 K\r\nprocess temperature [K]: generated using a random walk process normalized to a standard deviation of 1 K, added to the air temperature plus 10 K.\r\nrotational speed [rpm]: calculated from a power of 2860 W, overlaid with a normally distributed noise\r\ntorque [Nm]: torque values are normally distributed around 40 Nm with a Ïƒ = 10 Nm and no negative values. \r\ntool wear [min]: The quality variants H/M/L add 5/3/2 minutes of tool wear to the used tool in the process. and a\r\n'machine failure' label that indicates, whether the machine has failed in this particular datapoint for any of the following failure modes are true.\r\n\r\nThe machine failure consists of five independent failure modes\r\ntool wear failure (TWF): the tool will be replaced of fail at a randomly selected tool wear time between 200 â€“ 240 mins (120 times in our dataset). At this point in time, the tool is replaced 69 times, and fails 51 times (randomly assigned).\r\nheat dissipation failure (HDF): heat dissipation causes a process failure, if the difference between air- and process temperature is below 8.6 K and the toolâ€™s rotational speed is below 1380 rpm. This is the case for 115 data points.\r\npower failure (PWF): the product of torque and rotational speed (in rad/s) equals the power required for the process. If this power is below 3500 W or above 9000 W, the process fails, which is the case 95 times in our dataset.\r\noverstrain failure (OSF): if the product of tool wear and torque exceeds 11,000 minNm for the L product variant (12,000 M, 13,000 H), the process fails due to overstrain. This is true for 98 datapoints.\r\nrandom failures (RNF): each process has a chance of 0,1 % to fail regardless of its process parameters. This is the case for only 5 datapoints, less than could be expected for 10,000 datapoints in our dataset.\r\n\r\nIf at least one of the above failure modes is true, the process fails and the 'machine failure' label is set to 1. It is therefore not transparent to the machine learning method, which of the failure modes has caused the process to fail ", 'citation': None}}
                   name     role         type demographic description units  \
0                   UID       ID      Integer        None        None   NaN
1            Product ID       ID  Categorical        None        None   NaN
2                  Type  Feature  Categorical        None        None   NaN
3       Air temperature  Feature   Continuous        None        None     K
4   Process temperature  Feature   Continuous        None        None     K
5      Rotational speed  Feature      Integer        None        None   rpm
6                Torque  Feature   Continuous        None        None    Nm
7             Tool wear  Feature      Integer        None        None   min
8       Machine failure   Target      Integer        None        None   NaN
9                   TWF   Target      Integer        None        None   NaN
10                  HDF   Target      Integer        None        None   NaN
11                  PWF   Target      Integer        None        None   NaN
12                  OSF   Target      Integer        None        None   NaN
13                  RNF   Target      Integer        None        None   NaN

   missing_values
0              no
1              no
2              no
3              no
4              no
5              no
6              no
7              no
8              no
9              no
10             no
11             no
12             no
13             no

2. Verify data fetched

In [106]:
print(data.info() , f'\n')
print("Total missing values:", data.isnull().sum().sum(),)
data.tail(26)

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   UID                  10000 non-null  int64
 1   Product ID           10000 non-null  str
 2   Type                 10000 non-null  str
 3   Air temperature      10000 non-null  float64
 4   Process temperature  10000 non-null  float64
 5   Rotational speed     10000 non-null  int64
 6   Torque               10000 non-null  float64
 7   Tool wear            10000 non-null  int64
 8   Machine failure      10000 non-null  int64
 9   TWF                  10000 non-null  int64
 10  HDF                  10000 non-null  int64
 11  PWF                  10000 non-null  int64
 12  OSF                  10000 non-null  int64
 13  RNF                  10000 non-null  int64
dtypes: float64(3), int64(9), str(2)
memory usage: 1.1 MB
None

Total missing values: 0

,UID,Product ID,Type,Air temperature,Process temperature,Rotational speed,Torque,Tool wear,Machine failure,TWF,HDF,PWF,OSF,RNF
9974,9975,L57154,L,298.6,308.2,1361,68.2,172,1,0,0,1,1,0
9975,9976,M24835,M,298.6,308.3,1589,34.1,174,0,0,0,0,0,0
9976,9977,L57156,L,298.6,308.2,1705,26.3,177,0,0,0,0,0,0
9977,9978,L57157,L,298.6,308.3,1422,40.4,179,0,0,0,0,0,0
9978,9979,H39392,H,298.6,308.3,1377,52.1,181,0,0,0,0,0,0
9979,9980,L57159,L,298.5,308.3,1334,49.8,186,0,0,0,0,0,0
9980,9981,L57160,L,298.6,308.4,1559,36.6,188,0,0,0,0,0,0
9981,9982,L57161,L,298.7,308.5,1353,47.0,190,0,0,0,0,0,0
9982,9983,M24842,M,298.7,308.4,1507,45.7,192,0,0,0,0,0,0
9983,9984,L57163,L,298.7,308.4,1694,28.7,195,0,0,0,0,0,0
9984,9985,H39398,H,298.7,308.4,1432,42.8,197,0,0,0,0,0,0
9985,9986,H39399,H,298.7,308.5,1572,35.6,202,0,0,0,0,0,0
9986,9987,M24846,M,298.8,308.6,1507,42.3,207,0,0,0,0,0,0
9987,9988,M24847,M,298.8,308.6,1500,37.1,210,0,0,0,0,0,0
9988,9989,L57168,L,298.9,308.6,1771,24.1,213,0,0,0,0,0,0
9989,9990,M24849,M,298.8,308.5,1577,33.2,0,0,0,0,0,0,0
9990,9991,L57170,L,298.8,308.5,1527,36.2,3,0,0,0,0,0,0
9991,9992,M24851,M,298.9,308.4,1827,26.1,5,0,0,0,0,0,0
9992,9993,L57172,L,298.8,308.4,1484,39.2,8,0,0,0,0,0,0
9993,9994,L57173,L,298.8,308.4,1401,47.3,10,0,0,0,0,0,0
9994,9995,L57174,L,298.8,308.3,1634,27.9,12,0,0,0,0,0,0
9995,9996,M24855,M,298.8,308.4,1604,29.5,14,0,0,0,0,0,0
9996,9997,H39410,H,298.9,308.4,1632,31.8,17,0,0,0,0,0,0
9997,9998,M24857,M,299.0,308.6,1645,33.4,22,0,0,0,0,0,0
9998,9999,H39412,H,299.0,308.7,1408,48.5,25,0,0,0,0,0,0
9999,10000,M24859,M,299.0,308.7,1500,40.2,30,0,0,0,0,0,0

In [107]:
data["Product ID"].nunique()

10000

All Product IDs are unique. With this information, I can exclude the entire column from the model's dataset

3. Save dataset to /data/raw

The dataset will be saved as both a csv file, and as a schema enforced parquet file.
We will likely use the CSVs, but having a direct representation of the original doesn't hurt

In [108]:
# store datasets to data/raw (in both csv and parquet format)
data.to_csv(RAW_DATA_DIR / "ai4i2020.csv")
print(f"Original dataset saved to: {Path(RAW_DATA_DIR / "ai4i2020.csv")}")

data.to_parquet(RAW_DATA_DIR / "ai4i2020.parquet")
print(f"Original dataset saved to: {Path(RAW_DATA_DIR / "ai4i2020.parquet")}")

Original dataset saved to: ../data/raw/ai4i2020.csv
Original dataset saved to: ../data/raw/ai4i2020.parquet

4. Remove unneeded columns, examine feature engineering opportunities

In [109]:
# dropping UID and Product ID columns, as well as targets (twf, hdf, pwf, osf, and rnf)
model_data = data.drop(columns=["UID","Product ID","TWF","HDF","PWF","OSF","RNF"])

In [110]:
# one-hot encoding type to (H)igh, (M)edium, and (L)ow 
# Note: I'm using drop_first=False. This creates perfect multicolinearity. Linear models will struggle
# CAN BE CHANGED TO ORDINAL ENCODING FOR RANDOM FOREST MODEL
model_data = pd.get_dummies(model_data, columns=["Type"], drop_first=False)

In [111]:
# format column names to snake_case
model_data.columns = model_data.columns.str.lower().str.replace(" ", "_")
model_data.head()

,air_temperature,process_temperature,rotational_speed,torque,tool_wear,machine_failure,type_h,type_l,type_m
0,298.1,308.6,1551,42.8,0,0,False,False,True
1,298.2,308.7,1408,46.3,3,0,False,True,False
2,298.1,308.5,1498,49.4,5,0,False,True,False
3,298.2,308.6,1433,39.5,7,0,False,True,False
4,298.2,308.7,1408,40.0,9,0,False,True,False

5. Save processed data

In [ ]:
# store datasets to data/processed as csv
print(f"Processed dataset saved to: {Path(PROC_DATA_DIR / "ai4i2020_processed.csv")}")

Processed dataset saved to: ../data/processed/ai4i2020_processed.csv